### ISSUE TITLE
Working with active_admin?

### ISSUE THREAD

**Issue by antarr** [dnasseri/rails5-api-guide#1]
Have you gotten this to work with active_admin?

**Comment by nassredean** [comment]
@atbyrd sorry about the delay in response. I have not gotten this to work with active_admin. Actually I haven't used that library, but any PR's are welcome and if you have any specific errors I could try and help you diagnose. Thx!

**Comment by nassredean** [comment]
Sorry, looking at active_admin it seems like it relies on a number of middlewares that arent in rails api mode. I think this is probably not possible, or if it is, would require sacrificing a lot of the lite weightness of the rails api mode.
